### ISSUE TITLE
stop catching (and potentially throwing) assertion errors

### ISSUE THREAD

**Issue by ghost** [qdzo/ceylon-config#2]
Assertion errors in Ceylon indicate that something that should never happen in a correctly‐written program has happened; they are not meant to actually be caught. Catching them is not only bad practice, but it’s also inherently wrong by the definition of assertion errors.

Additionally, assertions are meant to check for *developer* input, and not *user* input. An uncaught assertion error implies that there is a bug in the program, and not that the user didn’t provide a necessary environment variable.

The correct thing to do would be to have your optional methods potentially return `null`, and have your existence‐asserting methods check for their result and throw something that is not an `AssertionError` in case they are `null` so that it can be caught by the developer for them to display a proper error message.

That is, instead of writing the following:

```Ceylon
shared String getString(Object key){
    assert(exists val = get(key));
    return val;
}

shared String? getStringOrNull(Object key){
    try {
        return getString(key);
    } catch(AssertionError ae) {
        return null;
    }
}
```

it is, by the definition of `AssertionError`, objectively more correct to write the following:

```Ceylon
shared String? getStringOrNull(Object key) => this[key];

shared String getString(Object key)
{
    if(exists string = getStringOrNull(key))
    {
        return(string);
    }
    else
    {
        throw(Something());
    }
}
```

Perhaps more subjectively, I really don’t think these type‐unsafe non‐`OrNull` methods are actually a good practice in Ceylon. Ideally you don’t want to give the user of your library the confidence that these values will exist, and instead, you should require them to actually act upon the possibility of them not existing.

**Comment by qdzo** [comment]
Thanks for some clarification about `AssertionError` usage. I agree with you in this point.

As I understands your second point right, you recommend to change api of given example methods

```ceylon
shared String? getStringOrNull(Object key);
shared String getString(Object key);
```

To something like in ceylon collections

```ceylon
shared String? getString(Object key);
shared String getStringOrDefault(Object key, String default);
```
If so, I don't agree with that. 
Purpose of type-unsafe methods is to fail-fast in entry point of your app. You could not start your app without some params, instead of starting with partial specified parameters. At this point I try to force library users to remove configuration from code.(It's good practice anyway)
But if you use unsafe methods from non-entry point function you may be surprised.

**Comment by qdzo** [comment]
Or maybe change methods from

```ceylon
shared String? getStringOrNull(Object key);
shared String getString(Object key);
```

to

```ceylon
shared String? getString(Object key);
shared String requireString(Object key);
```
If this adds any insight, I would change them.

**Comment by ghost** [comment]
Well, the thing is, if the value is required by the developer, they can fail themselves. As I said, having an uncaught assertion error (or, arguably, any throwable) indicates that there is a bug in the program, and not that some required input was not present. This failure needs to be in the form of a nice error message to the user, and not in the form of an unfriendly stack trace.

By the way, if you are saying that you tend to discourage people from using your library outside of the entry point (or at least too far away from it), I agree. In my opinion, that is even more reason to not include non‐`OrNull` methods because people can just test for the existence of those required parameters at the beginning of the entry point, and not do anything else in case they are not present.

**Comment by qdzo** [comment]
Well, as I said above I totally agree with you at the `AssertionError` and thanks for explanations.
BTW Ceylon already have such patterns as using `AssertionErrors` (see `ceylon.toml`). And this approach let you write less code for throwing. But your explanations showed differences in their usage. 
And there are one problem - we need more discipline from all devs to follow such usage recommendations  to rely on 'right' meaning of `AssertionError` .

**Comment by qdzo** [comment]
8f1ba047079dfc9c3fe5488379319e79c055f609

**Comment by qdzo** [comment]
Fixed in  

* 8f1ba047079dfc9c3fe5488379319e79c055f609
* 1f6f2d38f2d9b95e09ea84160c63074a68ff1974
